# Generated by Django 4.1.2 on 2023-01-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='status',
            field=models.CharField(choices=[('order-placed', 'order-placed'), ('in-cart', 'in-cart'), ('cancelled', 'cancelled')], default='order-placed', max_length=200),
        ),
    ]
